# Generated by Django 5.0 on 2023-12-19 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='images',
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 16, 41, 19, 787798), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
            ],
        ),
    ]
