# Generated by Django 5.0 on 2023-12-19 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartments_images_alter_apartments_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentImages',
            new_name='Images',
        ),
        migrations.AlterModelOptions(
            name='apartments',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 17, 40, 40, 569158), verbose_name='Дата публикации'),
        ),
    ]
