# Generated by Django 5.0 on 2023-12-19 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 17, 46, 8, 425789), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='images',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='apartments.apartments'),
        ),
    ]
