# Generated by Django 5.0 on 2023-12-20 07:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_apartments_date_alter_images_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 10, 30, 15, 277083), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='images',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartments'),
        ),
    ]
