# Generated by Django 5.0 on 2023-12-20 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartments_price_alter_apartments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 10, 31, 22, 258957), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
