# Generated by Django 5.0 on 2023-12-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_rename_images_images_image_alter_apartments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 10, 54, 2, 649689), verbose_name='Дата публикации'),
        ),
    ]
