# Generated by Django 5.0 on 2023-12-20 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_alter_apartments_date_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 11, 24, 11, 720571), verbose_name='Дата публикации'),
        ),
    ]
