# Generated by Django 5.0 on 2023-12-21 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_apartments_plan_apartments_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 9, 6, 13, 679929), verbose_name='Дата публикации'),
        ),
    ]
